module.exports = Object.freeze({
    CREATEROOM: 'create-room',
    DELETEROOM: 'DELETEROOM',
    GAMESTARTABLE: 'GAMESTARTABLE',
    PLAYERJOIN: "player-join",
    GAMEMESSAGE: "game-message",
    GAMESTART: "game-start",
    LOADPAGE: "LOADPAGE",
    LOADPAGESPECIFIC: "LOADPAGESPECIFIC",
    CHECKVIP: "CHECKVIP",
    TARGETEDGAMEMESSAGE: "TARGETEDGAMEMESSAGE",
    RELOG: "RELOG"
});